name: CI Pipeline

on:
  push:
    branches:
      - dev
      - test
      - main
  pull_request:
    branches:
      - dev
      - test
      - main

env:
    NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
    NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

jobs:
  lint:
    name: ES-Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Run ES-Lint
        run: bun run lint

  build:
    name: Build Next.js Application
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build Next.js
        run: bun run build
        
  cloudflare-simulation:
    name: Simulate Cloudflare Pages Environment
    runs-on: ubuntu-latest
    needs: build
    env:
      CF_PAGES: 1
      CF_PAGES_URL: http://localhost:8788
      CF_PAGES_BRANCH: ${{ github.ref_name }}
      CF_PAGES_COMMIT_SHA: ${{ github.sha }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for Cloudflare simulation
        run: |
          docker build -t cloudflare-pages-sim -f ./Dockerfile.cloudflare \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
            --build-arg CF_PAGES_BRANCH=${{ github.ref_name }} \
            --build-arg CF_PAGES_COMMIT_SHA=${{ github.sha }}

      - name: Run deployment simulation in Docker
        run: |
          docker run --rm \
            -e CF_PAGES=$CF_PAGES \
            -e CF_PAGES_BRANCH=$CF_PAGES_BRANCH \
            -e CF_PAGES_COMMIT_SHA=$CF_PAGES_COMMIT_SHA \
            -e CF_PAGES_URL=$CF_PAGES_URL \
            -e NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
            -e NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
            -v ${{ github.workspace }}:/app \
            cloudflare-pages-sim

      - name: Output simulation logs
        run: |
          echo "✅ Cloudflare Pages simulation completed"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"